# Generated by Django 2.2 on 2022-09-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='econtact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='ename',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='eemail',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
