# Generated by Django 2.2 on 2022-09-22 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_auto_20220922_1022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='ename',
        ),
    ]
