# Generated by Django 2.2 on 2022-09-22 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0004_auto_20220922_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='contact',
            new_name='econtact',
        ),
    ]
